### ISSUE TITLE
list doesn't seem to show all channels sometimes

### ISSUE THREAD

**Issue by koebi** [robustirc/robustirc#103]
Yesterday, I was invited (by someone messaging me) to join #zhn-kino on robustirc.
Yet, issuing /list didn't show the channel.
I was nevertheless able to connect to it just a few minutes later, and issuing /list again a quarter hour later showed the channel…
The screenshot below shows the output of the weechat "status" window for the two calls to /list.
![2015-04-03 23-44-03](https://cloud.githubusercontent.com/assets/4692974/6992871/59d733f8-dae1-11e4-8a39-731344720a69.png)

**Comment by stapelberg** [comment]
From your session:

```
MODE #zhn-kino
:robustirc.net 324 koebi #zhn-kino +rst
```

So, #zhn-kino is a secret channel, and it’s working as intended that these don’t show up in LIST (unless you are already in them).

**Comment by koebi** [comment]
I see. Thanks for the explanation, and sorry for bothering :)
