### ISSUE TITLE
Implement Querying for registration status

### ISSUE THREAD

**Issue by Merovius** [robustirc/robustirc#133]
I am writing a bot and I want it to only query something to a certain nick, if that nick is registered andauthenticated. For that, it would need a way to check, whether a nick is registered and whether the current user of that nick is authenticated. Apparently, WHOIS can be used for that, if the server implements it?

**Comment by stapelberg** [comment]
I think the reply code in question is `RPL_WHOISREGNICK` (307), e.g. on OFTC:
```
:helix.oftc.net 307 blergh sECuRE :user has identified to services
```
…or on mozilla:
```
:concrete.mozilla.org 307 testib flo :is a registered nick
```

ircd-hybrid (used by OFTC) sends that numeric out when the user has +r user mode:
```c
  if (HasUMode(target_p, UMODE_REGISTERED))
    sendto_one_numeric(source_p, &me, RPL_WHOISREGNICK, target_p->name);
```
