### ISSUE TITLE
running in docker is painful

### ISSUE THREAD

**Issue by mischief** [robustirc/robustirc#136]
currently the website documentation has an [example](https://robustirc.net/docs/adminguide.html#_installing_running) for running robustirc in docker, but the docker container changes user to nobody, and will encounter permission errors when using the mounted /var/lib/robustirc and certificates from the host.

the documentation should probably cover an appropriate way to configure this, since it is relatively unsuable as is.

FWIW, the host is coreos 1068.9.0.

**Comment by stapelberg** [comment]
Use `chown -R 99.99 /media/persistent/robustirc /media/persistent/ssl` to make the example work.

I’ll mention this in the docs in a second.

**Comment by stapelberg** [comment]
Please let me know if things are still unclear.

**Comment by mischief** [comment]
After various typos and permission errors related to letsencrypt i was able to set up a robust irc cluster on coreos :) fwiw having a bridge systemd docker unit would be helpful too.

**Comment by stapelberg** [comment]
I’m using the following two units:

(robustirc-bridge-nossl.service)
```
[Unit]
Description=RobustIRC public bridge (no SSL)
After=docker.service
Requires=docker.service

[Service]
Restart=always
StartLimitInterval=0

# Always pull the latest version (bleeding edge).
ExecStartPre=/usr/bin/docker pull robustirc/bridge:latest
ExecStartPre=-/usr/bin/docker kill bridge
ExecStartPre=-/usr/bin/docker rm -f bridge

ExecStart=/usr/bin/docker run \
  --name bridge \
  robustirc/bridge:latest \
    -network=robustirc.net

[Install]
WantedBy=multi-user.target
# So that a stop/start of docker will also start the RobustIRC bridge again.
WantedBy=docker.service
```

(robustirc-bridge-ssl.service)
```
[Unit]
Description=RobustIRC public bridge (SSL)
After=docker.service robustirc-bridge-nossl.service
Requires=docker.service robustirc-bridge-nossl.service

[Service]
Restart=always
StartLimitInterval=0

# Always pull the latest version (bleeding edge).
ExecStartPre=/usr/bin/docker pull robustirc/stunnel-bridge:latest

ExecStart=/usr/bin/docker run \
  -v /media/persistent:/media/persistent:ro \
  -p :6697:6697 \
  -p :7000:6697 \
  -p :9999:6697 \
  --link bridge:bridge \
  robustirc/stunnel-bridge:latest

[Install]
WantedBy=multi-user.target
# So that a stop/start of docker will also start the RobustIRC bridge again.
WantedBy=docker.service
```

Likely, the latter is not useful as-is, because you’ll need to modify the config file. See https://github.com/robustirc/stunnel-bridge for the Dockerfile/configfile.
