### ISSUE TITLE
Question about srv.TLSConfig.GetCertificate

### ISSUE THREAD

**Issue by Resisty** [robustirc/robustirc#156]
Hello, I found a post referencing your commit https://github.com/robustirc/robustirc/commit/3b83e51eeed62e3e5421f03023503bd6e8c34193 on stackoverflow (https://stackoverflow.com/a/40883377) but I'm having trouble using your code.

When I make the config assignment:
`srv.TLSConfig.GetCertificate = kpr.GetCertificateFunc()`
the application panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeac1]
goroutine 54 [running]:
panic(0x3b9a60, 0xc42000c0d0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
main.main.func1(0xc4203d0960, 0xc4203cd700)
	/Users/brian.auron/git/jive/code/common-services/lemur/src/lemur/main.go:77 +0x191
created by main.main
	/Users/brian.auron/git/jive/code/common-services/lemur/src/lemur/main.go:88 +0x545
```
The lines in question are:
```
 77         srv.TLSConfig.GetCertificate = kpr.GetCertificateFunc()
 78         ln, err := net.Listen("tcp", *Flags.HostPort)
 79         if err != nil {
 80             Logs.Errorf("Could not start tcp listener: %+v", err)
 81             panic(err)
 82         }
 83         tlsListener := tls.NewListener(tcpKeepAliveListener{ln.(*net.TCPListener)}, srv.TLSConfig)
 84         srv.Serve(tlsListener)
 85 //        if err := http.ListenAndServe(*Flags.HostPort, router); err != nil {
 86 //          Logs.Errorf("%+v", err)
 87 //        }
 88     }()
```
I'm not sure why; saving the function to an intermediate variable doesn't panic, but assigning that variable/function to `srv.TLSConfig.GetCertificate` panics as well.

I've basically lifted the code straight from your source so I'm not sure why I'm running into this issue. If you have any insight or advice, I'd really appreciate it. Thanks!

**Comment by stapelberg** [comment]
My first guess would be that your srv.TLSConfig is nil. It’s hard to say without having a reproducible code example, though.

**Comment by Resisty** [comment]
But... isn't that why I'm assigning to it? Or do you mean if it's nil to start with, assignment somehow fails?

**Comment by stapelberg** [comment]
You’re supposed to assign to the GetCertificate field of an existing (i.e. non-nil) srv.TLSConfig struct. If srv.TLSConfig itself is nil, that assignment will panic.

**Comment by Resisty** [comment]
Argh, I think you have it. It prints weird but maybe I just suck at fmt:
`75         Logs.Infof("WTF is our tlsconfig? %+v", srv.TLSConfig)`
`{"level":"info","message":"WTF is our tlsconfig? \u003cnil\u003e",...`

**Comment by stapelberg** [comment]
`\u003c` is `<`, `\u003e` is `>`, so this reads <nil> after json-unescaping, which confirms that srv.TLSConfig is nil. Set it and you should be good.

**Comment by Resisty** [comment]
```
 74         srv.TLSConfig = &tls.Config{
 75             GetCertificate: kpr.GetCertificateFunc(),
 76         }
```
It works, thanks so much!
