### ISSUE TITLE
Implement a test program for verifying robustness

### ISSUE THREAD

**Issue by stapelberg** [robustirc/robustirc#60]
I think such a program could work the following way:

1. It uses `robustirc-localnet` to bring up a new local network.
2. It directly uses `github.com/robustirc/bridge/robustsession` instead of talking to the bridge so that it can call GetMessages without specify lastseen, thereby getting the entire IRC output log and not just new messages. This is important for verifying that the that old messages are restored properly from snapshots/the log.
3. It connects to IRC and then does all of this at the same time:
  * after a random time interval in range [0, 1s] it sends a message to IRC
  * after a different random time interval in range [0, 1s] it kills a random number of servers.
4. After killing the server(s), it should make a copy of their state directory so that one can reproduce potential problems.
5. Then, it should restart the server(s) and verify that the network becomes consistent again and that every server returns the same IRC log as response to the GetMessages request.
6. Goto 3

Before doing releases, we could then leave this running for a day or so to make sure that the new release is as robust as the old one.

In a later version, it’d be cool to use fault injection to simulate other failures, such as a full disk, or a failing write.

**Comment by knweiss** [comment]
Just wondering: Did you consider using the [Jepsen](https://github.com/aphyr/jepsen) framework for testing? Jepsen examples: https://aphyr.com/tags/jepsen

**Comment by stapelberg** [comment]
@knweiss I’m aware of jepsen, but I’m not sure if it’s necessary to run jepsen against RobustIRC itself in comparison to running it on the raft library itself. Do you know more?

**Comment by knweiss** [comment]
Jepsen already [exposed some bugs in Raft implementations](https://aphyr.com/posts/316-call-me-maybe-etcd-and-consul).

I was just reading your (interesting!) RobustIRC slidedeck and was wondering if Jepsen could be used to test e.g. a "5 irc clients/5 irc servers" configuration during network partitions. I.e. to create a test suite of the entire system including clients.

**Comment by stapelberg** [comment]
I got jepsen to run, so let’s see if I can add a RobustIRC test.

**Comment by stapelberg** [comment]
See https://github.com/aphyr/jepsen/pull/80 for the jepsen RobustIRC test.

**Comment by stapelberg** [comment]
That pull request has been merged (and successfully tests RobustIRC), so I think we’re good.
